replicaCount: 1
name: k8s-demo-go-web-app
env: staging
namespace: staging
image:
  name: webserver-simple
  tag: 'd0271d39405ecd01e390f7ded310f0a1c98407e7'
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 8418
  targetPort: 8080
  portName: http