name: main CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: er-sanjaysah/preview_eks-demo
          ref: main

  build:
    runs-on: ubuntu-latest
    needs: clone
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: er-sanjaysah/preview_eks-demo
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: myimg/webserver-simple:${{ github.sha }}

  update_image_tag:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: er-sanjaysah/preview_eks-demo
          ref: main

      - name: Update k8s canary manifest
        uses: mikefarah/yq@v4
        with:
          command: yq eval -i '.image.tag = "${{ github.sha }}"' ./helm/values.yaml

      - name: Show updated values.yaml
        run: cat ./helm/values.yaml

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update image tag to myimg/webserver-simple:${{ github.sha }}
          branch: main
          file_pattern: ./helm/values.yaml