name: preview CI Workflow

on:
  pull_request:
    types: [labeled]

jobs:
  clone:
    if: contains(github.event.pull_request.labels.*.name, 'preview')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: er-sanjaysah/preview_eks-demo
          ref: ${{ github.head_ref }}
          
  build:
    if: contains(github.event.pull_request.labels.*.name, 'preview')
    runs-on: ubuntu-latest
    needs: clone
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: src
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: ssah6694/webserver-simple:${{ github.sha }}