name: PR Build Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get branch name
      id: branch-name
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./src/Dockerfile
        push: false
        tags: webserver-simple:${{ steps.branch-name.outputs.branch }}

    - name: Print image name
      run: echo "Built image: webserver-simple:${{ steps.branch-name.outputs.branch }}"